# Generated by Django 6.0.4 on 2026-04-27 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150, verbose_name='Тема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('points_max', models.PositiveIntegerField(default=0, verbose_name='Макс. кол. баллов')),
                ('points_check', models.PositiveIntegerField(default=0, verbose_name='Кол. баллов для зачета')),
                ('theme_type', models.CharField(choices=[('all', 'все отделы'), ('custom', 'указанные')], default='all', max_length=10, verbose_name='Доступность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для прохождения')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='Досупен с')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Досупен до')),
                ('departments', models.ManyToManyField(blank=True, to='user.department', verbose_name='Доступность для отделов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'theme',
            },
        ),
    ]
