# Generated by Django 6.0.3 on 2026-03-06 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Идентификатор темы', unique=True, verbose_name='Идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тема тестирования',
                'verbose_name_plural': 'Темы тестирования',
                'db_table': 'themes',
            },
            bases=('core.basemodel',),
        ),
    ]
