# Generated by Django 6.0.3 on 2026-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="check_points",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество баллов для зачета"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="points",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество баллов"
            ),
        ),
    ]
